src/Tupi/SecurityBundle/Form/SettingType.php
<?php
namespace Tupi\SecurityBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Length;


class SettingType extends AbstractType 
{	
	public function buildForm(FormBuilderInterface $builder, array $options)
	{	
		$builder->add('id', 'hidden')
		->add('title', 'text', array(
			'label' => 'Título',
			'required' => true,
			'constraints' => array(
				new NotBlank(array('message' => 'É necessário informar o título.')),
				new Length(array('max' => 150, 'maxMessage' => 'Limite de caracteres atingido.'))
			)
		))
		->add('description', 'textarea', array(
			'label' => 'Descrição',
			'required' => true,
		    'attr' => array('cols' => 30, 'rows' => 5),
			'constraints' => new NotBlank(array('message' => 'É necessário informar a descrição.'))
		))
		->add('metaKeywords', 'textarea', array(
			'label' => 'Palavras chaves',
			'required' => true,
		    'attr' => array('cols' => 30, 'rows' => 5),
			'constraints' => new NotBlank(array('message' => 'É necessário informar as palavras chaves.'))
		))	
		->add('ga', 'text', array(
		    'label' => 'Google Analytics',
		    'required' => false,
			'attr' => array('placeholder' => 'UA-########-#')
		))
		->add('fbSiteName', 'text', array(
			'label' => 'Nome do site',
			'required' => false
		))
		->add('fbTitle', 'text', array(
		    'label' => 'Título',
		    'required' => false
		))
		->add('fbDescription', 'text', array(
			'label' => 'Descrição',
		    'required' => false
		))
		->add('fbLink', 'text', array(
			'label' => 'Link',
		    'required' => false
		))
		->add('fbImage', 'text', array(
			'label' => 'Imagem',
			'required' => false
		))
		->add('fbId', 'text', array(
			'label' => 'Id Facebook',
			'required' => false,
			'attr' => array('placeholder' => '####################')
		));
	}
	
	public function getName()
	{
		return 'configuration';
	}

}

src/Tupi/SecurityBundle/Resources/views/Resource/cadastro.html.twig
{% extends 'TupiAdminBundle:Template:main.html.twig' %}
{% block botoes %}
	{{ admin.form_button('tupi_resource_home', 'Voltar', {'class': 'voltar'}) }}
	{{ admin.form_button('tupi_resource_new', 'Adicionar', {'class': 'adicionar'}) }}
	{{ admin.sbutton('Salvar', 'salvar', admin.id_by_name(form)) }}
{% endblock %}

{% set title_controle = title_controle ~ ' Funcionalidade' %}

{% block main %}
<div class="formulario esp_top">
	<div class="tabs row">
		
		{{ form_start(form) }}
			{{ form_row(form.id) }}
			<div id="geral" class="box">
				
				<ul class="col-md-6">
					<li>{{ form_row(form.name) }}</li>
				</ul>
				<ul class="col-md-6">
					<li>{{ form_row(form.path) }}</li>
				</ul>				
			</div>
		{{ form_end(form) }}
	</div>
</div>
{% endblock %}

src/Tupi/SecurityBundle/Resources/views/Resource/lista.html.twig
{% extends 'TupiAdminBundle:Template:admin-lista.html.twig' %}

{% set title = 'Funcionalidades' %}
{% set actions = {'tupi_resource_new': {'label': 'Adicionar', 'attrs': {'class': 'adicionar'} } } %}

{% block table_head %}
	<th class="titulo">Módulo</th>
	<th class="item3">URL</th>
{% endblock %}
{% block table_body %}
	<td><a href="{{ path('tupi_resource_edit', {'id':item.id}) }}">{{item.name}}</a></td>
	<td>{{item.path}}</td>
{% endblock %}		